// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://okmivclonffzlynqrlhz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9rbWl2Y2xvbmZmemx5bnFybGh6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg4NzM4ODksImV4cCI6MjA1NDQ0OTg4OX0.q4zkY3MT9e70MSwVTtlXhdl092IQh_OHjRvBSR7n3_o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);